### ISSUE TITLE
error about cookie

### ISSUE THREAD

**Issue by bouffon-celeste** [Schubilegend/SchubiRat#17]
[13:44:36] [Thread-12/INFO]: [dev.schubilegend.utils.Utils:decrypt:54]: java.lang.ArrayIndexOutOfBoundsException
[13:44:36] [Thread-12/INFO]: [dev.schubilegend.utils.Utils:decrypt:54]: 	at java.lang.System.arraycopy(Native Method)
[13:44:36] [Thread-12/INFO]: [dev.schubilegend.utils.Utils:decrypt:54]: 	at java.util.Arrays.copyOfRange(Arrays.java:3521)
[13:44:36] [Thread-12/INFO]: [dev.schubilegend.utils.Utils:decrypt:54]: 	at dev.schubilegend.utils.Utils.decrypt(Utils.java:46)
[13:44:36] [Thread-12/INFO]: [dev.schubilegend.utils.Utils:decrypt:54]: 	at dev.schubilegend.handlers.CookieHandler.crawlCookies(CookieHandler.java:83)
[13:44:36] [Thread-12/INFO]: [dev.schubilegend.utils.Utils:decrypt:54]: 	at dev.schubilegend.handlers.CookieHandler.crawlUserData(CookieHandler.java:56)
[13:44:36] [Thread-12/INFO]: [dev.schubilegend.utils.Utils:decrypt:54]: 	at dev.schubilegend.handlers.CookieHandler.grabCookies(CookieHandler.java:39)
[13:44:36] [Thread-12/INFO]: [dev.schubilegend.utils.Utils:decrypt:54]: 	at dev.schubilegend.SchubiMod.lambda$Init$1(SchubiMod.java:95)
[13:44:36] [Thread-12/INFO]: [dev.schubilegend.utils.Utils:decrypt:54]: 	at dev.schubilegend.SchubiMod$$Lambda$5/1150458225.run(Unknown Source)
[13:44:36] [Thread-12/INFO]: [dev.schubilegend.utils.Utils:decrypt:54]: 	at java.lang.Thread.run(Thread.java:745)
[13:44:36] [Thread-12/INFO]: [dev.schubilegend.handlers.CookieHandler:crawlCookies:94]: java.lang.NullPointerException
[13:44:36] [Thread-12/INFO]: [dev.schubilegend.handlers.CookieHandler:crawlCookies:94]: 	at dev.schubilegend.handlers.CookieHandler.crawlCookies(CookieHandler.java:84)
[13:44:36] [Thread-12/INFO]: [dev.schubilegend.handlers.CookieHandler:crawlCookies:94]: 	at dev.schubilegend.handlers.CookieHandler.crawlUserData(CookieHandler.java:56)
[13:44:36] [Thread-12/INFO]: [dev.schubilegend.handlers.CookieHandler:crawlCookies:94]: 	at dev.schubilegend.handlers.CookieHandler.grabCookies(CookieHandler.java:39)
[13:44:36] [Thread-12/INFO]: [dev.schubilegend.handlers.CookieHandler:crawlCookies:94]: 	at dev.schubilegend.SchubiMod.lambda$Init$1(SchubiMod.java:95)
[13:44:36] [Thread-12/INFO]: [dev.schubilegend.handlers.CookieHandler:crawlCookies:94]: 	at dev.schubilegend.SchubiMod$$Lambda$5/1150458225.run(Unknown Source)
[13:44:36] [Thread-12/INFO]: [dev.schubilegend.handlers.CookieHandler:crawlCookies:94]: 	at java.lang.Thread.run(Thread.java:745)
[13:44:36] [Thread-12/INFO]: [dev.schubilegend.utils.Utils:decrypt:54]: java.lang.ArrayIndexOutOfBoundsException
[13:44:36] [Thread-12/INFO]: [dev.schubilegend.utils.Utils:decrypt:54]: 	at java.lang.System.arraycopy(Native Method)
[13:44:36] [Thread-12/INFO]: [dev.schubilegend.utils.Utils:decrypt:54]: 	at java.util.Arrays.copyOfRange(Arrays.java:3521)
[13:44:36] [Thread-12/INFO]: [dev.schubilegend.utils.Utils:decrypt:54]: 	at dev.schubilegend.utils.Utils.decrypt(Utils.java:46)
[13:44:36] [Thread-12/INFO]: [dev.schubilegend.utils.Utils:decrypt:54]: 	at dev.schubilegend.handlers.CookieHandler.crawlCookies(CookieHandler.java:83)
[13:44:36] [Thread-12/INFO]: [dev.schubilegend.utils.Utils:decrypt:54]: 	at dev.schubilegend.handlers.CookieHandler.crawlUserData(CookieHandler.java:56)
[13:44:36] [Thread-12/INFO]: [dev.schubilegend.utils.Utils:decrypt:54]: 	at dev.schubilegend.handlers.CookieHandler.grabCookies(CookieHandler.java:39)
[13:44:36] [Thread-12/INFO]: [dev.schubilegend.utils.Utils:decrypt:54]: 	at dev.schubilegend.SchubiMod.lambda$Init$1(SchubiMod.java:95)
[13:44:36] [Thread-12/INFO]: [dev.schubilegend.utils.Utils:decrypt:54]: 	at dev.schubilegend.SchubiMod$$Lambda$5/1150458225.run(Unknown Source)
[13:44:36] [Thread-12/INFO]: [dev.schubilegend.utils.Utils:decrypt:54]: 	at java.lang.Thread.run(Thread.java:745)
[13:44:36] [Thread-12/INFO]: [dev.schubilegend.handlers.CookieHandler:crawlCookies:94]: java.lang.NullPointerException
[13:44:36] [Thread-12/INFO]: [dev.schubilegend.handlers.CookieHandler:crawlCookies:94]: 	at dev.schubilegend.handlers.CookieHandler.crawlCookies(CookieHandler.java:84)
[13:44:36] [Thread-12/INFO]: [dev.schubilegend.handlers.CookieHandler:crawlCookies:94]: 	at dev.schubilegend.handlers.CookieHandler.crawlUserData(CookieHandler.java:56)
[13:44:36] [Thread-12/INFO]: [dev.schubilegend.handlers.CookieHandler:crawlCookies:94]: 	at dev.schubilegend.handlers.CookieHandler.grabCookies(CookieHandler.java:39)
[13:44:36] [Thread-12/INFO]: [dev.schubilegend.handlers.CookieHandler:crawlCookies:94]: 	at dev.schubilegend.SchubiMod.lambda$Init$1(SchubiMod.java:95)
[13:44:36] [Thread-12/INFO]: [dev.schubilegend.handlers.CookieHandler:crawlCookies:94]: 	at dev.schubilegend.SchubiMod$$Lambda$5/1150458225.run(Unknown Source)
[13:44:36] [Thread-12/INFO]: [dev.schubilegend.handlers.CookieHandler:crawlCookies:94]: 	at java.lang.Thread.run(Thread.java:745)

**Comment by bouffon-celeste** [comment]
do you have any idea how to fix that? (i've did the recaf method)

**Comment by bouffon-celeste** [comment]
i haven't received anything on discord
